/* tslint:disable */
/* eslint-disable */
/**
 * Farcaster Hub API
 * Perform basic queries of Farcaster state via the REST API of a Farcaster hub. See the [Farcaster docs](https://www.thehubble.xyz/docs/httpapi/httpapi.html) for more details. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ErrorResponse } from '../models';
// @ts-ignore
import type { FetchUserFollowing200Response } from '../models';
// @ts-ignore
import type { LinkAdd } from '../models';
// @ts-ignore
import type { LinkType } from '../models';
/**
 * LinksApi - axios parameter creator
 * @export
 */
export const LinksApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary To target FID
         * @param {number} target_fid The FID of the target of the link 
         * @param {LinkType} [link_type] The type of link, as a string value 
         * @param {number} [page_size] Maximum number of messages to return in a single response 
         * @param {boolean} [reverse] Reverse the sort order, returning latest messages first 
         * @param {string} [page_token] The page token returned by the previous query, to fetch the next page. If this parameter is empty, fetch the first page 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         * @returns {Promise<FetchUserFollowing200Response>} A promise that resolves to a `FetchUserFollowing200Response` object
         * 
         * For more information, refer to the [API documentation](https://docs.neynar.com/reference/fetch-user-followers)
         * 
         */
        fetchUserFollowers: async (target_fid: number, link_type?: LinkType, page_size?: number, reverse?: boolean, page_token?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'target_fid' is not null or undefined
            assertParamExists('fetchUserFollowers', 'target_fid', target_fid)
            const localVarPath = `/v1/linksByTargetFid`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-key", configuration)

            if (target_fid !== undefined) {
                localVarQueryParameter['target_fid'] = target_fid;
            }

            if (link_type !== undefined) {
                localVarQueryParameter['link_type'] = link_type;
            }

            if (page_size !== undefined) {
                localVarQueryParameter['pageSize'] = page_size;
            }

            if (reverse !== undefined) {
                localVarQueryParameter['reverse'] = reverse;
            }

            if (page_token !== undefined) {
                localVarQueryParameter['pageToken'] = page_token;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary From source FID
         * @param {number} fid The FID of the link\&#39;s originator 
         * @param {LinkType} [link_type] The type of link, as a string value 
         * @param {number} [page_size] Maximum number of messages to return in a single response 
         * @param {boolean} [reverse] Reverse the sort order, returning latest messages first 
         * @param {string} [page_token] The page token returned by the previous query, to fetch the next page. If this parameter is empty, fetch the first page 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         * @returns {Promise<FetchUserFollowing200Response>} A promise that resolves to a `FetchUserFollowing200Response` object
         * 
         * For more information, refer to the [API documentation](https://docs.neynar.com/reference/fetch-user-following)
         * 
         */
        fetchUserFollowing: async (fid: number, link_type?: LinkType, page_size?: number, reverse?: boolean, page_token?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'fid' is not null or undefined
            assertParamExists('fetchUserFollowing', 'fid', fid)
            const localVarPath = `/v1/linksByFid`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-key", configuration)

            if (fid !== undefined) {
                localVarQueryParameter['fid'] = fid;
            }

            if (link_type !== undefined) {
                localVarQueryParameter['link_type'] = link_type;
            }

            if (page_size !== undefined) {
                localVarQueryParameter['pageSize'] = page_size;
            }

            if (reverse !== undefined) {
                localVarQueryParameter['reverse'] = reverse;
            }

            if (page_token !== undefined) {
                localVarQueryParameter['pageToken'] = page_token;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary By its FID and target FID.
         * @param {number} fid The FID of the link\&#39;s originator 
         * @param {number} target_fid The FID of the target of the link 
         * @param {LinkType} link_type The type of link, as a string value 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         * @returns {Promise<LinkAdd>} A promise that resolves to a `LinkAdd` object
         * 
         * For more information, refer to the [API documentation](https://docs.neynar.com/reference/lookup-user-relation)
         * 
         */
        lookupUserRelation: async (fid: number, target_fid: number, link_type: LinkType, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'fid' is not null or undefined
            assertParamExists('lookupUserRelation', 'fid', fid)
            // verify required parameter 'target_fid' is not null or undefined
            assertParamExists('lookupUserRelation', 'target_fid', target_fid)
            // verify required parameter 'link_type' is not null or undefined
            assertParamExists('lookupUserRelation', 'link_type', link_type)
            const localVarPath = `/v1/linkById`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-key", configuration)

            if (fid !== undefined) {
                localVarQueryParameter['fid'] = fid;
            }

            if (target_fid !== undefined) {
                localVarQueryParameter['target_fid'] = target_fid;
            }

            if (link_type !== undefined) {
                localVarQueryParameter['link_type'] = link_type;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LinksApi - functional programming interface
 * @export
 */
export const LinksApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = LinksApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary To target FID
         * @param {number} target_fid The FID of the target of the link 
         * @param {LinkType} [link_type] The type of link, as a string value 
         * @param {number} [page_size] Maximum number of messages to return in a single response 
         * @param {boolean} [reverse] Reverse the sort order, returning latest messages first 
         * @param {string} [page_token] The page token returned by the previous query, to fetch the next page. If this parameter is empty, fetch the first page 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         * @returns {Promise<FetchUserFollowing200Response>} A promise that resolves to a `FetchUserFollowing200Response` object
         * 
         * For more information, refer to the [API documentation](https://docs.neynar.com/reference/fetch-user-followers)
         * 
         */
        async fetchUserFollowers(target_fid: number, link_type?: LinkType, page_size?: number, reverse?: boolean, page_token?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FetchUserFollowing200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fetchUserFollowers(target_fid, link_type, page_size, reverse, page_token, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LinksApi.fetchUserFollowers']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary From source FID
         * @param {number} fid The FID of the link\&#39;s originator 
         * @param {LinkType} [link_type] The type of link, as a string value 
         * @param {number} [page_size] Maximum number of messages to return in a single response 
         * @param {boolean} [reverse] Reverse the sort order, returning latest messages first 
         * @param {string} [page_token] The page token returned by the previous query, to fetch the next page. If this parameter is empty, fetch the first page 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         * @returns {Promise<FetchUserFollowing200Response>} A promise that resolves to a `FetchUserFollowing200Response` object
         * 
         * For more information, refer to the [API documentation](https://docs.neynar.com/reference/fetch-user-following)
         * 
         */
        async fetchUserFollowing(fid: number, link_type?: LinkType, page_size?: number, reverse?: boolean, page_token?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FetchUserFollowing200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fetchUserFollowing(fid, link_type, page_size, reverse, page_token, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LinksApi.fetchUserFollowing']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary By its FID and target FID.
         * @param {number} fid The FID of the link\&#39;s originator 
         * @param {number} target_fid The FID of the target of the link 
         * @param {LinkType} link_type The type of link, as a string value 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         * @returns {Promise<LinkAdd>} A promise that resolves to a `LinkAdd` object
         * 
         * For more information, refer to the [API documentation](https://docs.neynar.com/reference/lookup-user-relation)
         * 
         */
        async lookupUserRelation(fid: number, target_fid: number, link_type: LinkType, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LinkAdd>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.lookupUserRelation(fid, target_fid, link_type, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LinksApi.lookupUserRelation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * LinksApi - factory interface
 * @export
 */
export const LinksApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = LinksApiFp(configuration)
    return {
        /**
         * 
         * @summary To target FID
         * @param {LinksApiFetchUserFollowersRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         * @returns {Promise<FetchUserFollowing200Response>} A promise that resolves to a `FetchUserFollowing200Response` object
         * 
         * For more information, refer to the [API documentation](https://docs.neynar.com/reference/fetch-user-followers)
         * 
         */
        fetchUserFollowers(requestParameters: LinksApiFetchUserFollowersRequest, options?: RawAxiosRequestConfig): AxiosPromise<FetchUserFollowing200Response> {
            return localVarFp.fetchUserFollowers(requestParameters.target_fid, requestParameters.link_type, requestParameters.page_size, requestParameters.reverse, requestParameters.page_token, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary From source FID
         * @param {LinksApiFetchUserFollowingRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         * @returns {Promise<FetchUserFollowing200Response>} A promise that resolves to a `FetchUserFollowing200Response` object
         * 
         * For more information, refer to the [API documentation](https://docs.neynar.com/reference/fetch-user-following)
         * 
         */
        fetchUserFollowing(requestParameters: LinksApiFetchUserFollowingRequest, options?: RawAxiosRequestConfig): AxiosPromise<FetchUserFollowing200Response> {
            return localVarFp.fetchUserFollowing(requestParameters.fid, requestParameters.link_type, requestParameters.page_size, requestParameters.reverse, requestParameters.page_token, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary By its FID and target FID.
         * @param {LinksApiLookupUserRelationRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         * @returns {Promise<LinkAdd>} A promise that resolves to a `LinkAdd` object
         * 
         * For more information, refer to the [API documentation](https://docs.neynar.com/reference/lookup-user-relation)
         * 
         */
        lookupUserRelation(requestParameters: LinksApiLookupUserRelationRequest, options?: RawAxiosRequestConfig): AxiosPromise<LinkAdd> {
            return localVarFp.lookupUserRelation(requestParameters.fid, requestParameters.target_fid, requestParameters.link_type, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * LinksApi - interface
 * @export
 * @interface LinksApi
 */
export interface LinksApiInterface {
    /**
     * 
     * @summary To target FID
     * @param {LinksApiFetchUserFollowersRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LinksApiInterface
     * @returns {Promise<FetchUserFollowing200Response>} A promise that resolves to a `FetchUserFollowing200Response` object
     * 
     * For more information, refer to the [API documentation](https://docs.neynar.com/reference/fetch-user-followers)
     * 
     */
    fetchUserFollowers(requestParameters: LinksApiFetchUserFollowersRequest, options?: RawAxiosRequestConfig): AxiosPromise<FetchUserFollowing200Response>;

    /**
     * 
     * @summary From source FID
     * @param {LinksApiFetchUserFollowingRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LinksApiInterface
     * @returns {Promise<FetchUserFollowing200Response>} A promise that resolves to a `FetchUserFollowing200Response` object
     * 
     * For more information, refer to the [API documentation](https://docs.neynar.com/reference/fetch-user-following)
     * 
     */
    fetchUserFollowing(requestParameters: LinksApiFetchUserFollowingRequest, options?: RawAxiosRequestConfig): AxiosPromise<FetchUserFollowing200Response>;

    /**
     * 
     * @summary By its FID and target FID.
     * @param {LinksApiLookupUserRelationRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LinksApiInterface
     * @returns {Promise<LinkAdd>} A promise that resolves to a `LinkAdd` object
     * 
     * For more information, refer to the [API documentation](https://docs.neynar.com/reference/lookup-user-relation)
     * 
     */
    lookupUserRelation(requestParameters: LinksApiLookupUserRelationRequest, options?: RawAxiosRequestConfig): AxiosPromise<LinkAdd>;

}

/**
 * Request parameters for fetchUserFollowers operation in LinksApi.
 * @export
 * @interface LinksApiFetchUserFollowersRequest
 */
export interface LinksApiFetchUserFollowersRequest {
    /**
     * The FID of the target of the link
     * 
     * 
     * 
     * @type {number}
     * @memberof LinksApiFetchUserFollowers
     */
    readonly target_fid: number

    /**
     * The type of link, as a string value
     * 
     * 
     * 
     * @type {LinkType}
     * @memberof LinksApiFetchUserFollowers
     */
    readonly link_type?: LinkType

    /**
     * Maximum number of messages to return in a single response
     * 
     * 
     * 
     * @type {number}
     * @memberof LinksApiFetchUserFollowers
     */
    readonly page_size?: number

    /**
     * Reverse the sort order, returning latest messages first
     * 
     * 
     * 
     * @type {boolean}
     * @memberof LinksApiFetchUserFollowers
     */
    readonly reverse?: boolean

    /**
     * The page token returned by the previous query, to fetch the next page. If this parameter is empty, fetch the first page
     * 
     * 
     * 
     * @type {string}
     * @memberof LinksApiFetchUserFollowers
     */
    readonly page_token?: string
}

/**
 * Request parameters for fetchUserFollowing operation in LinksApi.
 * @export
 * @interface LinksApiFetchUserFollowingRequest
 */
export interface LinksApiFetchUserFollowingRequest {
    /**
     * The FID of the link\&#39;s originator
     * 
     * 
     * 
     * @type {number}
     * @memberof LinksApiFetchUserFollowing
     */
    readonly fid: number

    /**
     * The type of link, as a string value
     * 
     * 
     * 
     * @type {LinkType}
     * @memberof LinksApiFetchUserFollowing
     */
    readonly link_type?: LinkType

    /**
     * Maximum number of messages to return in a single response
     * 
     * 
     * 
     * @type {number}
     * @memberof LinksApiFetchUserFollowing
     */
    readonly page_size?: number

    /**
     * Reverse the sort order, returning latest messages first
     * 
     * 
     * 
     * @type {boolean}
     * @memberof LinksApiFetchUserFollowing
     */
    readonly reverse?: boolean

    /**
     * The page token returned by the previous query, to fetch the next page. If this parameter is empty, fetch the first page
     * 
     * 
     * 
     * @type {string}
     * @memberof LinksApiFetchUserFollowing
     */
    readonly page_token?: string
}

/**
 * Request parameters for lookupUserRelation operation in LinksApi.
 * @export
 * @interface LinksApiLookupUserRelationRequest
 */
export interface LinksApiLookupUserRelationRequest {
    /**
     * The FID of the link\&#39;s originator
     * 
     * 
     * 
     * @type {number}
     * @memberof LinksApiLookupUserRelation
     */
    readonly fid: number

    /**
     * The FID of the target of the link
     * 
     * 
     * 
     * @type {number}
     * @memberof LinksApiLookupUserRelation
     */
    readonly target_fid: number

    /**
     * The type of link, as a string value
     * 
     * 
     * 
     * @type {LinkType}
     * @memberof LinksApiLookupUserRelation
     */
    readonly link_type: LinkType
}

/**
 * LinksApi - object-oriented interface
 * @export
 * @class LinksApi
 * @extends {BaseAPI}
 */
export class LinksApi extends BaseAPI implements LinksApiInterface {
    /**
     * 
     * @summary To target FID
     * @param {LinksApiFetchUserFollowersRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LinksApi
     * @returns {Promise<FetchUserFollowing200Response>} A promise that resolves to a `FetchUserFollowing200Response` object
     * 
     * For more information, refer to the [API documentation](https://docs.neynar.com/reference/fetch-user-followers)
     * 
     */
    public fetchUserFollowers(requestParameters: LinksApiFetchUserFollowersRequest, options?: RawAxiosRequestConfig) {
        return LinksApiFp(this.configuration).fetchUserFollowers(requestParameters.target_fid, requestParameters.link_type, requestParameters.page_size, requestParameters.reverse, requestParameters.page_token, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary From source FID
     * @param {LinksApiFetchUserFollowingRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LinksApi
     * @returns {Promise<FetchUserFollowing200Response>} A promise that resolves to a `FetchUserFollowing200Response` object
     * 
     * For more information, refer to the [API documentation](https://docs.neynar.com/reference/fetch-user-following)
     * 
     */
    public fetchUserFollowing(requestParameters: LinksApiFetchUserFollowingRequest, options?: RawAxiosRequestConfig) {
        return LinksApiFp(this.configuration).fetchUserFollowing(requestParameters.fid, requestParameters.link_type, requestParameters.page_size, requestParameters.reverse, requestParameters.page_token, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary By its FID and target FID.
     * @param {LinksApiLookupUserRelationRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LinksApi
     * @returns {Promise<LinkAdd>} A promise that resolves to a `LinkAdd` object
     * 
     * For more information, refer to the [API documentation](https://docs.neynar.com/reference/lookup-user-relation)
     * 
     */
    public lookupUserRelation(requestParameters: LinksApiLookupUserRelationRequest, options?: RawAxiosRequestConfig) {
        return LinksApiFp(this.configuration).lookupUserRelation(requestParameters.fid, requestParameters.target_fid, requestParameters.link_type, options).then((request) => request(this.axios, this.basePath));
    }
}

