/* tslint:disable */
/* eslint-disable */
/**
 * Neynar API
 * The Neynar API allows you to interact with the Farcaster protocol among other things. See the [Neynar docs](https://docs.neynar.com/reference) for more details.
 *
 * The version of the OpenAPI document: 3.183.0
 * Contact: team@neynar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { Billing200Response } from '../models';
// @ts-ignore
import type { Billing400Response } from '../models';
/**
 * OrganizationApi - axios parameter creator
 * @export
 */
export const OrganizationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieves billing and subscription details for the current organization, including plan status, product category, billing email, and effective plan.
         * @summary Get billing information for the current organization
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         * @returns {Promise<Billing200Response>} A promise that resolves to a `Billing200Response` object
         * 
         * For more information, refer to the [API documentation](https://docs.neynar.com/reference/billing)
         * 
         */
        billing: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/portal/organization/billing`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-key", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OrganizationApi - functional programming interface
 * @export
 */
export const OrganizationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = OrganizationApiAxiosParamCreator(configuration)
    return {
        /**
         * Retrieves billing and subscription details for the current organization, including plan status, product category, billing email, and effective plan.
         * @summary Get billing information for the current organization
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         * @returns {Promise<Billing200Response>} A promise that resolves to a `Billing200Response` object
         * 
         * For more information, refer to the [API documentation](https://docs.neynar.com/reference/billing)
         * 
         */
        async billing(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Billing200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.billing(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OrganizationApi.billing']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * OrganizationApi - factory interface
 * @export
 */
export const OrganizationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = OrganizationApiFp(configuration)
    return {
        /**
         * Retrieves billing and subscription details for the current organization, including plan status, product category, billing email, and effective plan.
         * @summary Get billing information for the current organization
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         * @returns {Promise<Billing200Response>} A promise that resolves to a `Billing200Response` object
         * 
         * For more information, refer to the [API documentation](https://docs.neynar.com/reference/billing)
         * 
         */
        billing(options?: RawAxiosRequestConfig): AxiosPromise<Billing200Response> {
            return localVarFp.billing(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * OrganizationApi - interface
 * @export
 * @interface OrganizationApi
 */
export interface OrganizationApiInterface {
    /**
     * Retrieves billing and subscription details for the current organization, including plan status, product category, billing email, and effective plan.
     * @summary Get billing information for the current organization
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrganizationApiInterface
     * @returns {Promise<Billing200Response>} A promise that resolves to a `Billing200Response` object
     * 
     * For more information, refer to the [API documentation](https://docs.neynar.com/reference/billing)
     * 
     */
    billing(options?: RawAxiosRequestConfig): AxiosPromise<Billing200Response>;

}

/**
 * OrganizationApi - object-oriented interface
 * @export
 * @class OrganizationApi
 * @extends {BaseAPI}
 */
export class OrganizationApi extends BaseAPI implements OrganizationApiInterface {
    /**
     * Retrieves billing and subscription details for the current organization, including plan status, product category, billing email, and effective plan.
     * @summary Get billing information for the current organization
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrganizationApi
     * @returns {Promise<Billing200Response>} A promise that resolves to a `Billing200Response` object
     * 
     * For more information, refer to the [API documentation](https://docs.neynar.com/reference/billing)
     * 
     */
    public billing(options?: RawAxiosRequestConfig) {
        return OrganizationApiFp(this.configuration).billing(options).then((request) => request(this.axios, this.basePath));
    }
}

