/* tslint:disable */
/* eslint-disable */
/**
 * Farcaster API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BanList } from './ban-list';
// May contain unused imports in some cases
// @ts-ignore
import { NextCursor } from './next-cursor';

/**
 * 
 * @export
 * @interface BanListResponse
 */
export interface BanListResponse {
    /**
     * 
     * @type {Array<BanList>}
     * @memberof BanListResponse
     */
    'blocks'?: Array<BanList>;
    /**
     * 
     * @type {NextCursor}
     * @memberof BanListResponse
     */
    'next': NextCursor;
}

