/* tslint:disable */
/* eslint-disable */
/**
 * Farcaster API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Cast } from './cast';
// May contain unused imports in some cases
// @ts-ignore
import { CastEmbeddedParentAuthor } from './cast-embedded-parent-author';
// May contain unused imports in some cases
// @ts-ignore
import { CastNotificationType } from './cast-notification-type';
// May contain unused imports in some cases
// @ts-ignore
import { CastViewerContext } from './cast-viewer-context';
// May contain unused imports in some cases
// @ts-ignore
import { CastWithInteractionsAllOf } from './cast-with-interactions-all-of';
// May contain unused imports in some cases
// @ts-ignore
import { CastWithInteractionsReactions } from './cast-with-interactions-reactions';
// May contain unused imports in some cases
// @ts-ignore
import { CastWithInteractionsReplies } from './cast-with-interactions-replies';
// May contain unused imports in some cases
// @ts-ignore
import { ChannelOrDehydratedChannel } from './channel-or-dehydrated-channel';
// May contain unused imports in some cases
// @ts-ignore
import { ChannelUserContext } from './channel-user-context';
// May contain unused imports in some cases
// @ts-ignore
import { Embed } from './embed';
// May contain unused imports in some cases
// @ts-ignore
import { Frame } from './frame';
// May contain unused imports in some cases
// @ts-ignore
import { User } from './user';

/**
 * @type CastWithInteractions
 * @export
 */
export type CastWithInteractions = Cast & CastWithInteractionsAllOf;


