/* tslint:disable */
/* eslint-disable */
/**
 * Farcaster API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { EmbedUrlMetadataVideoStreamInner } from './embed-url-metadata-video-stream-inner';

/**
 * 
 * @export
 * @interface EmbedUrlMetadataVideo
 */
export interface EmbedUrlMetadataVideo {
    /**
     * 
     * @type {number}
     * @memberof EmbedUrlMetadataVideo
     */
    'duration_s'?: number;
    /**
     * 
     * @type {Array<EmbedUrlMetadataVideoStreamInner>}
     * @memberof EmbedUrlMetadataVideo
     */
    'stream'?: Array<EmbedUrlMetadataVideoStreamInner>;
}

