/* tslint:disable */
/* eslint-disable */
/**
 * Farcaster API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PostCastReqBodyEmbedsCastIdProperties } from './post-cast-req-body-embeds-cast-id-properties';

/**
 * 
 * @export
 * @interface PostCastReqBodyEmbeds
 */
export interface PostCastReqBodyEmbeds {
    /**
     * 
     * @type {PostCastReqBodyEmbedsCastIdProperties}
     * @memberof PostCastReqBodyEmbeds
     */
    'cast_id'?: PostCastReqBodyEmbedsCastIdProperties;
    /**
     * 
     * @type {PostCastReqBodyEmbedsCastIdProperties}
     * @memberof PostCastReqBodyEmbeds
     */
    'castId'?: PostCastReqBodyEmbedsCastIdProperties;
    /**
     * 
     * @type {string}
     * @memberof PostCastReqBodyEmbeds
     */
    'url'?: string;
}

