/* tslint:disable */
/* eslint-disable */
/**
 * Farcaster API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RegisterSignerKeyReqBodySponsor
 */
export interface RegisterSignerKeyReqBodySponsor {
    /**
     * User identifier (unsigned integer)
     * @type {number}
     * @memberof RegisterSignerKeyReqBodySponsor
     */
    'fid': number;
    /**
     * Signature generated by the fid of the sponsor and the signature generated from signKeyRequest for the app.
     * @type {string}
     * @memberof RegisterSignerKeyReqBodySponsor
     */
    'signature': string;
}

