/* tslint:disable */
/* eslint-disable */
/**
 * Farcaster API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Signer
 */
export interface Signer {
    /**
     * UUID of the signer
     * @type {string}
     * @memberof Signer
     */
    'signer_uuid': string;
    /**
     * Ed25519 public key
     * @type {string}
     * @memberof Signer
     */
    'public_key': string;
    /**
     * 
     * @type {string}
     * @memberof Signer
     */
    'status': SignerStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof Signer
     */
    'signer_approval_url'?: string;
    /**
     * The unique identifier of a farcaster user (unsigned integer)
     * @type {number}
     * @memberof Signer
     */
    'fid'?: number;
}

export const SignerStatusEnum = {
    Generated: 'generated',
    PendingApproval: 'pending_approval',
    Approved: 'approved',
    Revoked: 'revoked'
} as const;

export type SignerStatusEnum = typeof SignerStatusEnum[keyof typeof SignerStatusEnum];


