/* tslint:disable */
/* eslint-disable */
/**
 * Farcaster API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { SubscribedToAllOf } from './subscribed-to-all-of';
// May contain unused imports in some cases
// @ts-ignore
import { Subscription } from './subscription';
// May contain unused imports in some cases
// @ts-ignore
import { SubscriptionMetadata } from './subscription-metadata';
// May contain unused imports in some cases
// @ts-ignore
import { SubscriptionPrice } from './subscription-price';
// May contain unused imports in some cases
// @ts-ignore
import { SubscriptionTier } from './subscription-tier';
// May contain unused imports in some cases
// @ts-ignore
import { SubscriptionToken } from './subscription-token';
// May contain unused imports in some cases
// @ts-ignore
import { User } from './user';

/**
 * @type SubscribedTo
 * @export
 */
export type SubscribedTo = SubscribedToAllOf & Subscription;


