/* tslint:disable */
/* eslint-disable */
/**
 * Farcaster API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserDehydrated
 */
export interface UserDehydrated {
    /**
     * 
     * @type {string}
     * @memberof UserDehydrated
     */
    'object': UserDehydratedObjectEnum;
    /**
     * The unique identifier of a farcaster user (unsigned integer)
     * @type {number}
     * @memberof UserDehydrated
     */
    'fid': number;
}

export const UserDehydratedObjectEnum = {
    UserDehydrated: 'user_dehydrated'
} as const;

export type UserDehydratedObjectEnum = typeof UserDehydratedObjectEnum[keyof typeof UserDehydratedObjectEnum];


