/* tslint:disable */
/* eslint-disable */
/**
 * Farcaster API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ValidateFrameRequest
 */
export interface ValidateFrameRequest {
    /**
     * Hexadecimal string of message bytes.
     * @type {string}
     * @memberof ValidateFrameRequest
     */
    'message_bytes_in_hex'?: string;
}

