/* tslint:disable */
/* eslint-disable */
/**
 * Farcaster API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { WarpcastComposerActionListResponseActionsInnerAction } from './warpcast-composer-action-list-response-actions-inner-action';

/**
 * 
 * @export
 * @interface WarpcastComposerActionListResponseActionsInner
 */
export interface WarpcastComposerActionListResponseActionsInner {
    /**
     * The name of the action.
     * @type {string}
     * @memberof WarpcastComposerActionListResponseActionsInner
     */
    'name'?: string;
    /**
     * The icon representing the action.
     * @type {string}
     * @memberof WarpcastComposerActionListResponseActionsInner
     */
    'icon'?: string;
    /**
     * A brief description of the action.
     * @type {string}
     * @memberof WarpcastComposerActionListResponseActionsInner
     */
    'description'?: string;
    /**
     * URL to learn more about the action.
     * @type {string}
     * @memberof WarpcastComposerActionListResponseActionsInner
     */
    'about_url'?: string;
    /**
     * URL of the action\'s image.
     * @type {string}
     * @memberof WarpcastComposerActionListResponseActionsInner
     */
    'image_url'?: string;
    /**
     * URL to perform the action.
     * @type {string}
     * @memberof WarpcastComposerActionListResponseActionsInner
     */
    'action_url'?: string;
    /**
     * 
     * @type {WarpcastComposerActionListResponseActionsInnerAction}
     * @memberof WarpcastComposerActionListResponseActionsInner
     */
    'action'?: WarpcastComposerActionListResponseActionsInnerAction;
    /**
     * Icon name for the action.
     * @type {string}
     * @memberof WarpcastComposerActionListResponseActionsInner
     */
    'octicon'?: string;
    /**
     * Number of times the action has been added.
     * @type {number}
     * @memberof WarpcastComposerActionListResponseActionsInner
     */
    'added_count'?: number;
    /**
     * Name of the application providing the action.
     * @type {string}
     * @memberof WarpcastComposerActionListResponseActionsInner
     */
    'app_name'?: string;
    /**
     * Author\'s Farcaster ID.
     * @type {number}
     * @memberof WarpcastComposerActionListResponseActionsInner
     */
    'author_fid'?: number;
    /**
     * Category of the action.
     * @type {string}
     * @memberof WarpcastComposerActionListResponseActionsInner
     */
    'category'?: string;
    /**
     * Object type, which is \"composer_action\".
     * @type {string}
     * @memberof WarpcastComposerActionListResponseActionsInner
     */
    'object'?: string;
}

