/* tslint:disable */
/* eslint-disable */
/**
 * Farcaster API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ZodErrorErrorsInner
 */
export interface ZodErrorErrorsInner {
    /**
     * 
     * @type {string}
     * @memberof ZodErrorErrorsInner
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof ZodErrorErrorsInner
     */
    'expected': string;
    /**
     * 
     * @type {string}
     * @memberof ZodErrorErrorsInner
     */
    'received': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ZodErrorErrorsInner
     */
    'path': Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ZodErrorErrorsInner
     */
    'message': string;
}

