/* tslint:disable */
/* eslint-disable */
/**
 * Farcaster API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Cast } from './cast';
// May contain unused imports in some cases
// @ts-ignore
import type { CastAuthor } from './cast-author';
// May contain unused imports in some cases
// @ts-ignore
import type { CastParentAuthor } from './cast-parent-author';
// May contain unused imports in some cases
// @ts-ignore
import type { CastType } from './cast-type';
// May contain unused imports in some cases
// @ts-ignore
import type { CastWithInteractionsAllOf } from './cast-with-interactions-all-of';
// May contain unused imports in some cases
// @ts-ignore
import type { CastWithInteractionsReactions } from './cast-with-interactions-reactions';
// May contain unused imports in some cases
// @ts-ignore
import type { CastWithInteractionsRecasts } from './cast-with-interactions-recasts';
// May contain unused imports in some cases
// @ts-ignore
import type { CastWithInteractionsReplies } from './cast-with-interactions-replies';
// May contain unused imports in some cases
// @ts-ignore
import type { EmbedUrl } from './embed-url';
// May contain unused imports in some cases
// @ts-ignore
import type { User } from './user';
// May contain unused imports in some cases
// @ts-ignore
import type { ViewerContext } from './viewer-context';

/**
 * @type CastWithInteractions
 * @export
 */
export type CastWithInteractions = Cast & CastWithInteractionsAllOf;


