/* tslint:disable */
/* eslint-disable */
/**
 * Farcaster Hub API
 * Perform basic queries of Farcaster state via the REST API of a Farcaster hub. See the [Neynar docs](https://docs.neynar.com/reference) for more details. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: team@neynar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { HashScheme } from './hash-scheme';
// May contain unused imports in some cases
// @ts-ignore
import type { MessageAllOf } from './message-all-of';
// May contain unused imports in some cases
// @ts-ignore
import type { MessageAllOfData } from './message-all-of-data';
// May contain unused imports in some cases
// @ts-ignore
import type { MessageCommon } from './message-common';
// May contain unused imports in some cases
// @ts-ignore
import type { SignatureScheme } from './signature-scheme';

/**
 * @type Message
 * A Message is a delta operation on the Farcaster network. The message protobuf is an envelope that wraps a MessageData object and contains a hash and signature which can verify its authenticity.
 * @export
 */
export type Message = MessageAllOf & MessageCommon;


