/* tslint:disable */
/* eslint-disable */
/**
 * Farcaster Hub API
 * Perform basic queries of Farcaster state via the REST API of a Farcaster hub. See the [Neynar docs](https://docs.neynar.com/reference) for more details. 
 *
 * The version of the OpenAPI document: 2.34.0
 * Contact: team@neynar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OnChainEventCommon } from './on-chain-event-common';
// May contain unused imports in some cases
// @ts-ignore
import type { OnChainEventStorageRentAllOf } from './on-chain-event-storage-rent-all-of';
// May contain unused imports in some cases
// @ts-ignore
import type { StorageRentEventBody } from './storage-rent-event-body';

/**
 * @type OnChainEventStorageRent
 * @export
 */
export type OnChainEventStorageRent = OnChainEventCommon & OnChainEventStorageRentAllOf;


