/* tslint:disable */
/* eslint-disable */
/**
 * Neynar API
 * The Neynar API allows you to interact with the Farcaster protocol among other things. See the [Neynar docs](https://docs.neynar.com/reference) for more details.
 *
 * The version of the OpenAPI document: 3.114.0
 * Contact: team@neynar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Details for notification setup, only present when event is notifications_enabled
 * @export
 * @interface AppHostGetEventResponseNotificationDetails
 */
export interface AppHostGetEventResponseNotificationDetails {
    /**
     * URL endpoint for sending notifications
     * @type {string}
     * @memberof AppHostGetEventResponseNotificationDetails
     */
    'url': string;
    /**
     * Token to use when sending notifications to this user
     * @type {string}
     * @memberof AppHostGetEventResponseNotificationDetails
     */
    'token': string;
}

