/* tslint:disable */
/* eslint-disable */
/**
 * Neynar API
 * The Neynar API allows you to interact with the Farcaster protocol among other things. See the [Neynar docs](https://docs.neynar.com/reference) for more details.
 *
 * The version of the OpenAPI document: 3.25.0
 * Contact: team@neynar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EncodedJsonFarcasterSignature } from './encoded-json-farcaster-signature';

/**
 * @type AppHostPostEventReqBodyOneOfSignedMessage
 * JFS-signed message containing the event payload. The message must be properly signed and contain valid event information.  Can be provided as a single string or json object.
 * @export
 */
export type AppHostPostEventReqBodyOneOfSignedMessage = EncodedJsonFarcasterSignature | string;


