/* tslint:disable */
/* eslint-disable */
/**
 * Neynar API
 * The Neynar API allows you to interact with the Farcaster protocol among other things. See the [Neynar docs](https://docs.neynar.com/reference) for more details.
 *
 * The version of the OpenAPI document: 3.98.0
 * Contact: team@neynar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AssociateDeployment200Response
 */
export interface AssociateDeployment200Response {
    /**
     * 
     * @type {boolean}
     * @memberof AssociateDeployment200Response
     */
    'success': boolean;
    /**
     * Status message from the miniapp generator
     * @type {string}
     * @memberof AssociateDeployment200Response
     */
    'message': string;
}

