/* tslint:disable */
/* eslint-disable */
/**
 * Farcaster API V2
 * The Farcaster API allows you to interact with the Farcaster protocol. See the [Neynar docs](https://docs.neynar.com/reference) for more details. 
 *
 * The version of the OpenAPI document: 2.42.0
 * Contact: team@neynar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CastsMetrics
 */
export interface CastsMetrics {
    /**
     * 
     * @type {string}
     * @memberof CastsMetrics
     */
    'start': string;
    /**
     * 
     * @type {number}
     * @memberof CastsMetrics
     */
    'resolution_in_seconds': number;
    /**
     * 
     * @type {number}
     * @memberof CastsMetrics
     */
    'cast_count': number;
}

