/* tslint:disable */
/* eslint-disable */
/**
 * Farcaster API V2
 * The Farcaster API allows you to interact with the Farcaster protocol. See the [Neynar docs](https://docs.neynar.com/reference) for more details. 
 *
 * The version of the OpenAPI document: 2.39.0
 * Contact: team@neynar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { User } from './user';
// May contain unused imports in some cases
// @ts-ignore
import type { UserDehydrated } from './user-dehydrated';
// May contain unused imports in some cases
// @ts-ignore
import type { UserExperimental } from './user-experimental';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProfile } from './user-profile';
// May contain unused imports in some cases
// @ts-ignore
import type { UserVerifiedAccountsInner } from './user-verified-accounts-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { UserVerifiedAddresses } from './user-verified-addresses';
// May contain unused imports in some cases
// @ts-ignore
import type { UserViewerContext } from './user-viewer-context';

/**
 * @type ChannelMemberUser
 * @export
 */
export type ChannelMemberUser = User | UserDehydrated;


