/* tslint:disable */
/* eslint-disable */
/**
 * Neynar API
 * The Neynar API allows you to interact with the Farcaster protocol among other things. See the [Neynar docs](https://docs.neynar.com/reference) for more details.
 *
 * The version of the OpenAPI document: 3.137.0
 * Contact: team@neynar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ChannelMemberChannel } from './channel-member-channel';
// May contain unused imports in some cases
// @ts-ignore
import type { ChannelMemberRole } from './channel-member-role';
// May contain unused imports in some cases
// @ts-ignore
import type { ChannelMemberUser } from './channel-member-user';

export interface ChannelMember {
    'object': ChannelMemberObjectEnum;
    'role': ChannelMemberRole;
    'user': ChannelMemberUser;
    'channel': ChannelMemberChannel;
}

export const ChannelMemberObjectEnum = {
    Member: 'member'
} as const;

export type ChannelMemberObjectEnum = typeof ChannelMemberObjectEnum[keyof typeof ChannelMemberObjectEnum];


