/* tslint:disable */
/* eslint-disable */
/**
 * Neynar API
 * The Neynar API allows you to interact with the Farcaster protocol among other things. See the [Neynar docs](https://docs.neynar.com/reference) for more details.
 *
 * The version of the OpenAPI document: 3.177.0
 * Contact: team@neynar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ChannelExternalLink } from './channel-external-link';
// May contain unused imports in some cases
// @ts-ignore
import type { ChannelUserContext } from './channel-user-context';
// May contain unused imports in some cases
// @ts-ignore
import type { TextRange } from './text-range';
// May contain unused imports in some cases
// @ts-ignore
import type { User } from './user';
// May contain unused imports in some cases
// @ts-ignore
import type { UserDehydrated } from './user-dehydrated';

export interface Channel {
    'created_at': string;
    'description'?: string;
    'description_mentioned_profiles'?: Array<UserDehydrated>;
    /**
     * Positions within the text (inclusive start, exclusive end) where each mention occurs.
     */
    'description_mentioned_profiles_ranges'?: Array<TextRange>;
    'external_link'?: ChannelExternalLink;
    /**
     * Number of followers the channel has.
     */
    'follower_count'?: number;
    /**
     * @deprecated
     */
    'hosts'?: Array<User>;
    'id': string;
    'image_url'?: string;
    'lead'?: User;
    'member_count'?: number;
    /**
     * Use `lead` instead.
     * @deprecated
     */
    'moderator'?: User;
    'moderator_fids'?: Array<number>;
    'name'?: string;
    'object': ChannelObjectEnum;
    'parent_url'?: string;
    'pinned_cast_hash'?: string;
    'url': string;
    'viewer_context'?: ChannelUserContext;
}

export const ChannelObjectEnum = {
    Channel: 'channel'
} as const;

export type ChannelObjectEnum = typeof ChannelObjectEnum[keyof typeof ChannelObjectEnum];


