/* tslint:disable */
/* eslint-disable */
/**
 * Farcaster API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ChannelFollowReqBody
 */
export interface ChannelFollowReqBody {
    /**
     * UUID of the signer. `signer_uuid` is paired with API key, you cannot use a `uuid` made with a different API key.
     * @type {string}
     * @memberof ChannelFollowReqBody
     */
    'signer_uuid': string;
    /**
     * The unique identifier of a farcaster channel
     * @type {string}
     * @memberof ChannelFollowReqBody
     */
    'channel_id': string;
}

