/* tslint:disable */
/* eslint-disable */
/**
 * Neynar API
 * The Neynar API allows you to interact with the Farcaster protocol among other things. See the [Neynar docs](https://docs.neynar.com/reference) for more details.
 *
 * The version of the OpenAPI document: 3.137.0
 * Contact: team@neynar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface DeployErc721RequestCollectionConfig {
    'contract_uri'?: string;
    /**
     * Max supply (0 = unlimited)
     */
    'max_supply'?: number;
    /**
     * Royalty in basis points (500 = 5%, max 2500 = 25%)
     */
    'royalty_bps'?: number;
    /**
     * Defaults to creator wallet
     */
    'royalty_recipient'?: string;
}

