/* tslint:disable */
/* eslint-disable */
/**
 * Neynar API
 * The Neynar API allows you to interact with the Farcaster protocol among other things. See the [Neynar docs](https://docs.neynar.com/reference) for more details.
 *
 * The version of the OpenAPI document: 3.137.0
 * Contact: team@neynar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface DeployToVercel200Response {
    /**
     * Whether the deployment succeeded
     */
    'success': boolean;
    /**
     * URL of the deployed Vercel app
     */
    'deployment_url'?: string;
    /**
     * Vercel project ID
     */
    'project_id'?: string;
    /**
     * Production URL under neynar.app domain
     */
    'production_url'?: string;
}

