/* tslint:disable */
/* eslint-disable */
/**
 * Farcaster API V2
 * The Farcaster API allows you to interact with the Farcaster protocol. See the [Neynar docs](https://docs.neynar.com/reference) for more details. 
 *
 * The version of the OpenAPI document: 2.41.1
 * Contact: team@neynar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EmbedUrlMetadataImage
 */
export interface EmbedUrlMetadataImage {
    /**
     * 
     * @type {number}
     * @memberof EmbedUrlMetadataImage
     */
    'height_px'?: number;
    /**
     * 
     * @type {number}
     * @memberof EmbedUrlMetadataImage
     */
    'width_px'?: number;
}

