/* tslint:disable */
/* eslint-disable */
/**
 * Neynar API
 * The Neynar API allows you to interact with the Farcaster protocol among other things. See the [Neynar docs](https://docs.neynar.com/reference) for more details.
 *
 * The version of the OpenAPI document: 3.182.0
 * Contact: team@neynar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface FarcasterManifestFrame {
    'button_title'?: string;
    /**
     * Detailed description of the configuration
     */
    'description'?: string;
    /**
     * URL of the hero image displayed for the configuration
     */
    'hero_image_url'?: string;
    'home_url': string;
    'icon_url': string;
    'image_url'?: string;
    'name': string;
    /**
     * Whether search engines should not index this configuration
     */
    'noindex'?: boolean;
    /**
     * Description used for Open Graph previews
     */
    'og_description'?: string;
    /**
     * Image URL used for Open Graph previews
     */
    'og_image_url'?: string;
    /**
     * Title used for Open Graph previews
     */
    'og_title'?: string;
    /**
     * Primary category the configuration belongs to
     */
    'primary_category'?: string;
    /**
     * URLs of screenshots showcasing the configuration
     */
    'screenshot_urls'?: Array<string>;
    'splash_background_color'?: string;
    'splash_image_url'?: string;
    /**
     * Short subtitle for the configuration
     */
    'subtitle'?: string;
    /**
     * Short tagline for the configuration
     */
    'tagline'?: string;
    /**
     * Tags associated with the configuration
     */
    'tags'?: Array<string>;
    'version': FarcasterManifestFrameVersionEnum;
    'webhook_url'?: string;
}

export const FarcasterManifestFrameVersionEnum = {
    _1: '1',
    _000: '0.0.0',
    _001: '0.0.1',
    Next: 'next'
} as const;

export type FarcasterManifestFrameVersionEnum = typeof FarcasterManifestFrameVersionEnum[keyof typeof FarcasterManifestFrameVersionEnum];


