/* tslint:disable */
/* eslint-disable */
/**
 * Farcaster API V2
 * The Farcaster API allows you to interact with the Farcaster protocol. See the [Neynar docs](https://docs.neynar.com/reference) for more details. 
 *
 * The version of the OpenAPI document: 2.7.1
 * Contact: team@neynar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ErrorRes } from './error-res';
// May contain unused imports in some cases
// @ts-ignore
import type { ZodError } from './zod-error';
// May contain unused imports in some cases
// @ts-ignore
import type { ZodErrorErrorsInner } from './zod-error-errors-inner';

/**
 * @type FetchFeedForYou400Response
 * @export
 */
export type FetchFeedForYou400Response = ErrorRes | ZodError;


