/* tslint:disable */
/* eslint-disable */
/**
 * Neynar API
 * The Neynar API allows you to interact with the Farcaster protocol among other things. See the [Neynar docs](https://docs.neynar.com/reference) for more details.
 *
 * The version of the OpenAPI document: 3.132.0
 * Contact: team@neynar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FarcasterManifest } from './farcaster-manifest';
// May contain unused imports in some cases
// @ts-ignore
import type { FetchRelevantFrames200ResponseRelevantFramesInnerFrameMetadata } from './fetch-relevant-frames200-response-relevant-frames-inner-frame-metadata';
// May contain unused imports in some cases
// @ts-ignore
import type { User } from './user';

/**
 * FrameV2 object
 * @export
 * @interface FetchRelevantFrames200ResponseRelevantFramesInnerFrame
 */
export interface FetchRelevantFrames200ResponseRelevantFramesInnerFrame {
    /**
     * Version of the mini app, \'next\' for v2, \'vNext\' for v1
     * @type {string}
     * @memberof FetchRelevantFrames200ResponseRelevantFramesInnerFrame
     */
    'version': string;
    /**
     * URL of the image
     * @type {string}
     * @memberof FetchRelevantFrames200ResponseRelevantFramesInnerFrame
     */
    'image': string;
    /**
     * Launch URL of the mini app
     * @type {string}
     * @memberof FetchRelevantFrames200ResponseRelevantFramesInnerFrame
     */
    'frames_url': string;
    /**
     * Button title of a mini app
     * @type {string}
     * @memberof FetchRelevantFrames200ResponseRelevantFramesInnerFrame
     */
    'title'?: string;
    /**
     * 
     * @type {FarcasterManifest}
     * @memberof FetchRelevantFrames200ResponseRelevantFramesInnerFrame
     */
    'manifest'?: FarcasterManifest;
    /**
     * 
     * @type {User}
     * @memberof FetchRelevantFrames200ResponseRelevantFramesInnerFrame
     */
    'author'?: User;
    /**
     * 
     * @type {FetchRelevantFrames200ResponseRelevantFramesInnerFrameMetadata}
     * @memberof FetchRelevantFrames200ResponseRelevantFramesInnerFrame
     */
    'metadata'?: FetchRelevantFrames200ResponseRelevantFramesInnerFrameMetadata;
}

