/* tslint:disable */
/* eslint-disable */
/**
 * Neynar API
 * The Neynar API allows you to interact with the Farcaster protocol among other things. See the [Neynar docs](https://docs.neynar.com/reference) for more details.
 *
 * The version of the OpenAPI document: 3.77.0
 * Contact: team@neynar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FrameActionButton } from './frame-action-button';
// May contain unused imports in some cases
// @ts-ignore
import type { FrameV1Input } from './frame-v1-input';
// May contain unused imports in some cases
// @ts-ignore
import type { FrameV1State } from './frame-v1-state';

/**
 * Mini app v1 object
 * @export
 * @interface FrameV1
 */
export interface FrameV1 {
    /**
     * Version of the mini app, \'next\' for v2, \'vNext\' for v1
     * @type {string}
     * @memberof FrameV1
     */
    'version': string;
    /**
     * URL of the image
     * @type {string}
     * @memberof FrameV1
     */
    'image': string;
    /**
     * Launch URL of the mini app
     * @type {string}
     * @memberof FrameV1
     */
    'frames_url': string;
    /**
     * 
     * @type {Array<FrameActionButton>}
     * @memberof FrameV1
     */
    'buttons'?: Array<FrameActionButton>;
    /**
     * Post URL to take an action on this mini app
     * @type {string}
     * @memberof FrameV1
     */
    'post_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof FrameV1
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof FrameV1
     */
    'image_aspect_ratio'?: string;
    /**
     * 
     * @type {FrameV1Input}
     * @memberof FrameV1
     */
    'input'?: FrameV1Input;
    /**
     * 
     * @type {FrameV1State}
     * @memberof FrameV1
     */
    'state'?: FrameV1State;
}

