/* tslint:disable */
/* eslint-disable */
/**
 * Farcaster API V2
 * The Farcaster API allows you to interact with the Farcaster protocol. See the [Neynar docs](https://docs.neynar.com/reference) for more details. 
 *
 * The version of the OpenAPI document: 2.26.0
 * Contact: team@neynar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FrameActionButton } from './frame-action-button';
// May contain unused imports in some cases
// @ts-ignore
import type { FrameBase } from './frame-base';
// May contain unused imports in some cases
// @ts-ignore
import type { FrameV1AllOf } from './frame-v1-all-of';
// May contain unused imports in some cases
// @ts-ignore
import type { FrameV1AllOfInput } from './frame-v1-all-of-input';
// May contain unused imports in some cases
// @ts-ignore
import type { FrameV1AllOfState } from './frame-v1-all-of-state';

/**
 * @type FrameV1
 * Frame v1 object
 * @export
 */
export type FrameV1 = FrameBase & FrameV1AllOf;


