/* tslint:disable */
/* eslint-disable */
/**
 * Neynar API
 * The Neynar API allows you to interact with the Farcaster protocol among other things. See the [Neynar docs](https://docs.neynar.com/reference) for more details.
 *
 * The version of the OpenAPI document: 3.28.0
 * Contact: team@neynar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Detailed breakdown of errors encountered during notification delivery.
 * @export
 * @interface GetNotificationCampaignStats200ResponseNotificationCampaignsInnerStatsErrorBreakdown
 */
export interface GetNotificationCampaignStats200ResponseNotificationCampaignsInnerStatsErrorBreakdown {
    /**
     * A record mapping delivery error types to their occurrence counts.
     * @type {{ [key: string]: number; }}
     * @memberof GetNotificationCampaignStats200ResponseNotificationCampaignsInnerStatsErrorBreakdown
     */
    'delivery_errors'?: { [key: string]: number; };
    /**
     * A record mapping HTTP status codes to their occurrence counts.
     * @type {{ [key: string]: number; }}
     * @memberof GetNotificationCampaignStats200ResponseNotificationCampaignsInnerStatsErrorBreakdown
     */
    'http_errors'?: { [key: string]: number; };
}

