/* tslint:disable */
/* eslint-disable */
/**
 * Neynar API
 * The Neynar API allows you to interact with the Farcaster protocol among other things. See the [Neynar docs](https://docs.neynar.com/reference) for more details.
 *
 * The version of the OpenAPI document: 3.1.1
 * Contact: team@neynar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetNotificationCampaignStats200ResponseNotificationCampaignsInnerStats } from './get-notification-campaign-stats200-response-notification-campaigns-inner-stats';

/**
 * 
 * @export
 * @interface GetNotificationCampaignStats200ResponseNotificationCampaignsInner
 */
export interface GetNotificationCampaignStats200ResponseNotificationCampaignsInner {
    /**
     * The unique identifier for the notification campaign.
     * @type {string}
     * @memberof GetNotificationCampaignStats200ResponseNotificationCampaignsInner
     */
    'id': string;
    /**
     * The title of the notification campaign.
     * @type {string}
     * @memberof GetNotificationCampaignStats200ResponseNotificationCampaignsInner
     */
    'title': string;
    /**
     * The body text of the notification.
     * @type {string}
     * @memberof GetNotificationCampaignStats200ResponseNotificationCampaignsInner
     */
    'body': string;
    /**
     * 
     * @type {string}
     * @memberof GetNotificationCampaignStats200ResponseNotificationCampaignsInner
     */
    'created_at': string;
    /**
     * 
     * @type {GetNotificationCampaignStats200ResponseNotificationCampaignsInnerStats}
     * @memberof GetNotificationCampaignStats200ResponseNotificationCampaignsInner
     */
    'stats': GetNotificationCampaignStats200ResponseNotificationCampaignsInnerStats;
}

