/* tslint:disable */
/* eslint-disable */
/**
 * Neynar API
 * The Neynar API allows you to interact with the Farcaster protocol among other things. See the [Neynar docs](https://docs.neynar.com/reference) for more details.
 *
 * The version of the OpenAPI document: 3.184.0
 * Contact: team@neynar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface GetTableSchema200ResponseColumnsInner {
    /**
     * Default value expression
     */
    'defaultValue': string | null;
    /**
     * Whether the column is part of primary key
     */
    'isPrimaryKey': boolean;
    /**
     * Column name
     */
    'name': string;
    /**
     * Whether the column allows NULL values
     */
    'nullable': boolean;
    /**
     * Ordinal position in table
     */
    'position': number;
    /**
     * Column data type
     */
    'type': string;
}

