/* tslint:disable */
/* eslint-disable */
/**
 * Neynar API
 * The Neynar API allows you to interact with the Farcaster protocol among other things. See the [Neynar docs](https://docs.neynar.com/reference) for more details.
 *
 * The version of the OpenAPI document: 3.137.0
 * Contact: team@neynar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface GetConversationMessages200ResponseMessagesInner {
    /**
     * Message ID
     */
    'id': string;
    /**
     * Creation timestamp
     */
    'created_at': string;
    /**
     * Conversation ID
     */
    'conversation_id': string;
    /**
     * Message content
     */
    'message': string;
    /**
     * Message origin
     */
    'origin': GetConversationMessages200ResponseMessagesInnerOriginEnum;
    /**
     * Message type
     */
    'type'?: string;
    /**
     * Message subtype
     */
    'subtype'?: string;
}

export const GetConversationMessages200ResponseMessagesInnerOriginEnum = {
    User: 'user',
    System: 'system',
    Admin: 'admin'
} as const;

export type GetConversationMessages200ResponseMessagesInnerOriginEnum = typeof GetConversationMessages200ResponseMessagesInnerOriginEnum[keyof typeof GetConversationMessages200ResponseMessagesInnerOriginEnum];


