/* tslint:disable */
/* eslint-disable */
/**
 * Neynar API
 * The Neynar API allows you to interact with the Farcaster protocol among other things. See the [Neynar docs](https://docs.neynar.com/reference) for more details.
 *
 * The version of the OpenAPI document: 3.137.0
 * Contact: team@neynar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetTableSchema200ResponseColumnsInner } from './get-table-schema200-response-columns-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { GetTableSchema200ResponseForeignKeysInner } from './get-table-schema200-response-foreign-keys-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { GetTableSchema200ResponseIndexesInner } from './get-table-schema200-response-indexes-inner';

export interface GetTableSchema200Response {
    /**
     * Table name
     */
    'tableName': string;
    /**
     * Table columns
     */
    'columns': Array<GetTableSchema200ResponseColumnsInner>;
    /**
     * Table indexes
     */
    'indexes': Array<GetTableSchema200ResponseIndexesInner>;
    /**
     * Foreign key relationships
     */
    'foreignKeys': Array<GetTableSchema200ResponseForeignKeysInner>;
    /**
     * Primary key column names
     */
    'primaryKeyColumns': Array<string>;
}

