/* tslint:disable */
/* eslint-disable */
/**
 * Neynar API
 * The Neynar API allows you to interact with the Farcaster protocol among other things. See the [Neynar docs](https://docs.neynar.com/reference) for more details.
 *
 * The version of the OpenAPI document: 3.135.0
 * Contact: team@neynar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetTokenMetadata200ResponseToken } from './get-token-metadata200-response-token';

/**
 * 
 * @export
 * @interface GetTokenMetadata200Response
 */
export interface GetTokenMetadata200Response {
    /**
     * 
     * @type {GetTokenMetadata200ResponseToken}
     * @memberof GetTokenMetadata200Response
     */
    'token': GetTokenMetadata200ResponseToken;
}

