/* tslint:disable */
/* eslint-disable */
/**
 * Farcaster API V2
 * The Farcaster API allows you to interact with the Farcaster protocol. See the [Neynar docs](https://docs.neynar.com/reference) for more details. 
 *
 * The version of the OpenAPI document: 2.38.2
 * Contact: team@neynar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { HtmlMetadataAllOf } from './html-metadata-all-of';
// May contain unused imports in some cases
// @ts-ignore
import type { HtmlMetadataAllOfOembed } from './html-metadata-all-of-oembed';
// May contain unused imports in some cases
// @ts-ignore
import type { ImageObject } from './image-object';
// May contain unused imports in some cases
// @ts-ignore
import type { OgObject } from './og-object';
// May contain unused imports in some cases
// @ts-ignore
import type { VideoObject } from './video-object';

/**
 * @type HtmlMetadata
 * @export
 */
export type HtmlMetadata = HtmlMetadataAllOf & OgObject;


