/* tslint:disable */
/* eslint-disable */
/**
 * Neynar API
 * The Neynar API allows you to interact with the Farcaster protocol among other things. See the [Neynar docs](https://docs.neynar.com/reference) for more details.
 *
 * The version of the OpenAPI document: 3.170.0
 * Contact: team@neynar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ListSecrets200ResponseSecretsInner {
    /**
     * Environment variable name
     */
    'key': string;
    /**
     * Environment variable ID
     */
    'id': string;
    /**
     * Whether this is a system-managed or user-defined variable
     */
    'type': ListSecrets200ResponseSecretsInnerTypeEnum;
    /**
     * Masked preview of the secret value (e.g. \"sk_l…t1b3\")
     */
    'preview'?: string;
}

export const ListSecrets200ResponseSecretsInnerTypeEnum = {
    System: 'system',
    User: 'user'
} as const;

export type ListSecrets200ResponseSecretsInnerTypeEnum = typeof ListSecrets200ResponseSecretsInnerTypeEnum[keyof typeof ListSecrets200ResponseSecretsInnerTypeEnum];


