/* tslint:disable */
/* eslint-disable */
/**
 * Neynar API
 * The Neynar API allows you to interact with the Farcaster protocol among other things. See the [Neynar docs](https://docs.neynar.com/reference) for more details.
 *
 * The version of the OpenAPI document: 3.117.0
 * Contact: team@neynar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ListDeploymentFiles200ResponseFilesInner
 */
export interface ListDeploymentFiles200ResponseFilesInner {
    /**
     * File or directory name
     * @type {string}
     * @memberof ListDeploymentFiles200ResponseFilesInner
     */
    'name': string;
    /**
     * Full path relative to gen/
     * @type {string}
     * @memberof ListDeploymentFiles200ResponseFilesInner
     */
    'path': string;
    /**
     * Whether this is a directory
     * @type {boolean}
     * @memberof ListDeploymentFiles200ResponseFilesInner
     */
    'is_directory': boolean;
}

