/* tslint:disable */
/* eslint-disable */
/**
 * Neynar API
 * The Neynar API allows you to interact with the Farcaster protocol among other things. See the [Neynar docs](https://docs.neynar.com/reference) for more details.
 *
 * The version of the OpenAPI document: 3.136.0
 * Contact: team@neynar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Resolved mint recipient.
 * @export
 * @interface MintNft200ResponseTransactionsInnerOneOfRecipient
 */
export interface MintNft200ResponseTransactionsInnerOneOfRecipient {
    /**
     * Ethereum address
     * @type {string}
     * @memberof MintNft200ResponseTransactionsInnerOneOfRecipient
     */
    'address': string;
    /**
     * 
     * @type {number}
     * @memberof MintNft200ResponseTransactionsInnerOneOfRecipient
     */
    'quantity': number;
    /**
     * The unique identifier of a farcaster user or app (unsigned integer)
     * @type {number}
     * @memberof MintNft200ResponseTransactionsInnerOneOfRecipient
     */
    'fid'?: number;
}

