/* tslint:disable */
/* eslint-disable */
/**
 * Neynar API
 * The Neynar API allows you to interact with the Farcaster protocol among other things. See the [Neynar docs](https://docs.neynar.com/reference) for more details.
 *
 * The version of the OpenAPI document: 3.135.0
 * Contact: team@neynar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MintNft200ResponseTransactionsInnerOneOfReceipt } from './mint-nft200-response-transactions-inner-one-of-receipt';
// May contain unused imports in some cases
// @ts-ignore
import type { MintNft200ResponseTransactionsInnerOneOfRecipient } from './mint-nft200-response-transactions-inner-one-of-recipient';

/**
 * Successful mint transaction.
 * @export
 * @interface MintNft200ResponseTransactionsInnerOneOf
 */
export interface MintNft200ResponseTransactionsInnerOneOf {
    /**
     * 
     * @type {MintNft200ResponseTransactionsInnerOneOfRecipient}
     * @memberof MintNft200ResponseTransactionsInnerOneOf
     */
    'recipient': MintNft200ResponseTransactionsInnerOneOfRecipient;
    /**
     * Hexadecimal number expressed as string with \'0x\' prefix
     * @type {string}
     * @memberof MintNft200ResponseTransactionsInnerOneOf
     */
    'transaction_hash': string;
    /**
     * 
     * @type {MintNft200ResponseTransactionsInnerOneOfReceipt}
     * @memberof MintNft200ResponseTransactionsInnerOneOf
     */
    'receipt'?: MintNft200ResponseTransactionsInnerOneOfReceipt | null;
}

