/* tslint:disable */
/* eslint-disable */
/**
 * Neynar API
 * The Neynar API allows you to interact with the Farcaster protocol among other things. See the [Neynar docs](https://docs.neynar.com/reference) for more details.
 *
 * The version of the OpenAPI document: 3.183.0
 * Contact: team@neynar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PostCastReqBodyEmbedsAnyOf } from './post-cast-req-body-embeds-any-of';
// May contain unused imports in some cases
// @ts-ignore
import type { PostCastReqBodyEmbedsAnyOf1 } from './post-cast-req-body-embeds-any-of1';
// May contain unused imports in some cases
// @ts-ignore
import type { PostCastReqBodyEmbedsAnyOf2 } from './post-cast-req-body-embeds-any-of2';
// May contain unused imports in some cases
// @ts-ignore
import type { PostCastReqBodyEmbedsCastIdProperties } from './post-cast-req-body-embeds-cast-id-properties';

export interface PostCastReqBodyEmbeds {
    'cast_id': PostCastReqBodyEmbedsCastIdProperties;
    'castId': PostCastReqBodyEmbedsCastIdProperties;
    'url': string;
}

