/* tslint:disable */
/* eslint-disable */
/**
 * Neynar API
 * The Neynar API allows you to interact with the Farcaster protocol among other things. See the [Neynar docs](https://docs.neynar.com/reference) for more details.
 *
 * The version of the OpenAPI document: 3.85.0
 * Contact: team@neynar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PostCastReqBodyEmbedsCastIdProperties } from './post-cast-req-body-embeds-cast-id-properties';
// May contain unused imports in some cases
// @ts-ignore
import type { PostCastReqBodyEmbedsOneOf } from './post-cast-req-body-embeds-one-of';
// May contain unused imports in some cases
// @ts-ignore
import type { PostCastReqBodyEmbedsOneOf1 } from './post-cast-req-body-embeds-one-of1';
// May contain unused imports in some cases
// @ts-ignore
import type { PostCastReqBodyEmbedsOneOf2 } from './post-cast-req-body-embeds-one-of2';

/**
 * @type PostCastReqBodyEmbeds
 * @export
 */
export type PostCastReqBodyEmbeds = PostCastReqBodyEmbedsOneOf | PostCastReqBodyEmbedsOneOf1 | PostCastReqBodyEmbedsOneOf2;


