/* tslint:disable */
/* eslint-disable */
/**
 * Neynar API
 * The Neynar API allows you to interact with the Farcaster protocol among other things. See the [Neynar docs](https://docs.neynar.com/reference) for more details.
 *
 * The version of the OpenAPI document: 3.176.0
 * Contact: team@neynar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PromptDeploymentStreamRequestImagesInner } from './prompt-deployment-stream-request-images-inner';

export interface PromptDeploymentStreamRequest {
    /**
     * Optional conversation ID to continue an existing chat. If not provided, a new conversation will be created.
     */
    'conversation_id'?: string;
    /**
     * Deployment ID (UUID). Required if name not provided.
     */
    'deployment_id'?: string;
    /**
     * Farcaster ID of the user; if not provided, namespace must be provided
     */
    'fid'?: number;
    /**
     * Optional images for multimodal messages. Each image is base64-encoded.
     */
    'images'?: Array<PromptDeploymentStreamRequestImagesInner>;
    /**
     * Kubernetes deployment name. Required if deployment_id not provided.
     */
    'name'?: string;
    /**
     * Optional Kubernetes namespace. If not provided, will query for the active namespace for the given FID.
     */
    'namespace'?: string;
    /**
     * Prompt string to send to the deployment
     */
    'prompt': string;
    /**
     * Optional Claude SDK session ID to resume an existing Claude Code session. Enables session-based conversation continuity.
     */
    'session_id'?: string;
    /**
     * System prompt variant to use. Defaults to stable if not provided.
     */
    'system_prompt_variant'?: PromptDeploymentStreamRequestSystemPromptVariantEnum;
}

export const PromptDeploymentStreamRequestSystemPromptVariantEnum = {
    Canary: 'canary',
    Beta: 'beta',
    Stable: 'stable'
} as const;

export type PromptDeploymentStreamRequestSystemPromptVariantEnum = typeof PromptDeploymentStreamRequestSystemPromptVariantEnum[keyof typeof PromptDeploymentStreamRequestSystemPromptVariantEnum];


