/* tslint:disable */
/* eslint-disable */
/**
 * Neynar API
 * The Neynar API allows you to interact with the Farcaster protocol among other things. See the [Neynar docs](https://docs.neynar.com/reference) for more details.
 *
 * The version of the OpenAPI document: 3.29.0
 * Contact: team@neynar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RegisterUserOnChainReqBodyPreRegistrationCallsInner } from './register-user-on-chain-req-body-pre-registration-calls-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { RegisterUserOnChainReqBodyRegistration } from './register-user-on-chain-req-body-registration';
// May contain unused imports in some cases
// @ts-ignore
import type { RegisterUserOnChainReqBodySignersInner } from './register-user-on-chain-req-body-signers-inner';

/**
 * 
 * @export
 * @interface RegisterUserOnChainReqBody
 */
export interface RegisterUserOnChainReqBody {
    /**
     * An Idempotency key is a unique identifier for the request. **Note:**  1) Pre-registration calls must be idempotent when using idempotency keys. 2) This is used to prevent duplicate requests. Use the same idem key on retry attempts. 3) This should be a unique identifier for each request. 4) Recommended format is a 16-character string generated by the developer at the time of making this request.
     * @type {string}
     * @memberof RegisterUserOnChainReqBody
     */
    'idem'?: string;
    /**
     * 
     * @type {Array<RegisterUserOnChainReqBodyPreRegistrationCallsInner>}
     * @memberof RegisterUserOnChainReqBody
     */
    'pre_registration_calls'?: Array<RegisterUserOnChainReqBodyPreRegistrationCallsInner>;
    /**
     * 
     * @type {RegisterUserOnChainReqBodyRegistration}
     * @memberof RegisterUserOnChainReqBody
     */
    'registration': RegisterUserOnChainReqBodyRegistration;
    /**
     * 
     * @type {number}
     * @memberof RegisterUserOnChainReqBody
     */
    'storage_units'?: number;
    /**
     * 
     * @type {Array<RegisterUserOnChainReqBodySignersInner>}
     * @memberof RegisterUserOnChainReqBody
     */
    'signers'?: Array<RegisterUserOnChainReqBodySignersInner>;
}

