/* tslint:disable */
/* eslint-disable */
/**
 * Farcaster API V2
 * The Farcaster API allows you to interact with the Farcaster protocol. See the [Neynar docs](https://docs.neynar.com/reference) for more details. 
 *
 * The version of the OpenAPI document: 2.46.0
 * Contact: team@neynar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RegisterUserOnChainReqBodyPreRegistrationCallsInner
 */
export interface RegisterUserOnChainReqBodyPreRegistrationCallsInner {
    /**
     * 
     * @type {string}
     * @memberof RegisterUserOnChainReqBodyPreRegistrationCallsInner
     */
    'target': string;
    /**
     * Value in wei to send with the transaction. This is not the amount of ETH that will be sent, but rather the value of the transaction.
     * @type {number}
     * @memberof RegisterUserOnChainReqBodyPreRegistrationCallsInner
     */
    'value'?: number;
    /**
     * 
     * @type {string}
     * @memberof RegisterUserOnChainReqBodyPreRegistrationCallsInner
     */
    'data': string;
    /**
     * Set it to true if you want to ignore the failure of this call. If set to false, the registration will fail if this call fails.
     * @type {boolean}
     * @memberof RegisterUserOnChainReqBodyPreRegistrationCallsInner
     */
    'allow_failure'?: boolean;
}

