/* tslint:disable */
/* eslint-disable */
/**
 * Neynar API
 * The Neynar API allows you to interact with the Farcaster protocol among other things. See the [Neynar docs](https://docs.neynar.com/reference) for more details.
 *
 * The version of the OpenAPI document: 3.175.0
 * Contact: team@neynar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RegisterUserReqBodyMetadataLocation } from './register-user-req-body-metadata-location';
// May contain unused imports in some cases
// @ts-ignore
import type { RegisterUserReqBodyMetadataVerifiedAccounts } from './register-user-req-body-metadata-verified-accounts';

export interface RegisterUserReqBodyMetadata {
    'bio'?: string;
    'display_name'?: string;
    'location'?: RegisterUserReqBodyMetadataLocation;
    'pfp_url'?: string;
    'url'?: string;
    'username'?: string;
    'verified_accounts'?: RegisterUserReqBodyMetadataVerifiedAccounts;
}

