/* tslint:disable */
/* eslint-disable */
/**
 * Neynar API
 * The Neynar API allows you to interact with the Farcaster protocol among other things. See the [Neynar docs](https://docs.neynar.com/reference) for more details.
 *
 * The version of the OpenAPI document: 3.3.2
 * Contact: team@neynar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SignedKeyRequestSponsor1
 */
export interface SignedKeyRequestSponsor1 {
    /**
     * The unique identifier of a farcaster user or app (unsigned integer)
     * @type {number}
     * @memberof SignedKeyRequestSponsor1
     */
    'fid'?: number;
    /**
     * Signature generated by the fid of the sponsor and the signature generated from signKeyRequest for the app.
     * @type {string}
     * @memberof SignedKeyRequestSponsor1
     */
    'signature'?: string;
    /**
     * Neynar will sponsor the signer if set to true. **Note: ** If sponsor.fid and sponsor.signature are provided along with sponsored_by_neynar set to true, the sponsor.fid and sponsor.signature will be ignored. Neynar will sponsor the signer on behalf of the user. The developer will get charged in compute units.
     * @type {boolean}
     * @memberof SignedKeyRequestSponsor1
     */
    'sponsored_by_neynar'?: boolean;
}

