/* tslint:disable */
/* eslint-disable */
/**
 * Neynar API
 * The Neynar API allows you to interact with the Farcaster protocol among other things. See the [Neynar docs](https://docs.neynar.com/reference) for more details.
 *
 * The version of the OpenAPI document: 3.111.0
 * Contact: team@neynar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface StartAppRequest
 */
export interface StartAppRequest {
    /**
     * Farcaster ID of the user; if not provided, namespace must be provided
     * @type {number}
     * @memberof StartAppRequest
     */
    'fid'?: number;
    /**
     * Kubernetes deployment name
     * @type {string}
     * @memberof StartAppRequest
     */
    'name': string;
    /**
     * Optional Kubernetes namespace. If not provided, will query for the active namespace for the given FID.
     * @type {string}
     * @memberof StartAppRequest
     */
    'namespace'?: string;
}

