/* tslint:disable */
/* eslint-disable */
/**
 * Neynar API
 * The Neynar API allows you to interact with the Farcaster protocol among other things. See the [Neynar docs](https://docs.neynar.com/reference) for more details.
 *
 * The version of the OpenAPI document: 3.77.0
 * Contact: team@neynar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SubscriptionTier } from './subscription-tier';

/**
 * 
 * @export
 * @interface SubscriptionCheckResponseValue
 */
export interface SubscriptionCheckResponseValue {
    /**
     * 
     * @type {string}
     * @memberof SubscriptionCheckResponseValue
     */
    'object': SubscriptionCheckResponseValueObjectEnum;
    /**
     * 
     * @type {boolean}
     * @memberof SubscriptionCheckResponseValue
     */
    'status': boolean;
    /**
     * 
     * @type {number}
     * @memberof SubscriptionCheckResponseValue
     */
    'expires_at': number | null;
    /**
     * 
     * @type {number}
     * @memberof SubscriptionCheckResponseValue
     */
    'subscribed_at': number | null;
    /**
     * 
     * @type {SubscriptionTier}
     * @memberof SubscriptionCheckResponseValue
     */
    'tier': SubscriptionTier | null;
}

export const SubscriptionCheckResponseValueObjectEnum = {
    SubscribedToDehydrated: 'subscribed_to_dehydrated'
} as const;

export type SubscriptionCheckResponseValueObjectEnum = typeof SubscriptionCheckResponseValueObjectEnum[keyof typeof SubscriptionCheckResponseValueObjectEnum];


