/* tslint:disable */
/* eslint-disable */
/**
 * Neynar API
 * The Neynar API allows you to interact with the Farcaster protocol among other things. See the [Neynar docs](https://docs.neynar.com/reference) for more details.
 *
 * The version of the OpenAPI document: 3.132.0
 * Contact: team@neynar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateRowsRequest
 */
export interface UpdateRowsRequest {
    /**
     * Deployment ID (UUID)
     * @type {string}
     * @memberof UpdateRowsRequest
     */
    'deployment_id': string;
    /**
     * Farcaster ID of the user. Required for non-admin users.
     * @type {number}
     * @memberof UpdateRowsRequest
     */
    'fid'?: number;
    /**
     * Column values to update
     * @type {{ [key: string]: any | null; }}
     * @memberof UpdateRowsRequest
     */
    'set': { [key: string]: any | null; };
    /**
     * WHERE conditions (equality only, required)
     * @type {{ [key: string]: any | null; }}
     * @memberof UpdateRowsRequest
     */
    'where': { [key: string]: any | null; };
    /**
     * Maximum rows to update (default: 1000)
     * @type {number}
     * @memberof UpdateRowsRequest
     */
    'limit'?: number;
}

