/* tslint:disable */
/* eslint-disable */
/**
 * Neynar API
 * The Neynar API allows you to interact with the Farcaster protocol among other things. See the [Neynar docs](https://docs.neynar.com/reference) for more details.
 *
 * The version of the OpenAPI document: 3.171.0
 * Contact: team@neynar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UploadTokenMetadataRequestTokensInner } from './upload-token-metadata-request-tokens-inner';

export interface UploadTokenMetadataRequest {
    /**
     * Ethereum address
     */
    'contract_address': string;
    'network': UploadTokenMetadataRequestNetworkEnum;
    'tokens': Array<UploadTokenMetadataRequestTokensInner>;
}

export const UploadTokenMetadataRequestNetworkEnum = {
    Base: 'base',
    Optimism: 'optimism',
    BaseSepolia: 'base-sepolia'
} as const;

export type UploadTokenMetadataRequestNetworkEnum = typeof UploadTokenMetadataRequestNetworkEnum[keyof typeof UploadTokenMetadataRequestNetworkEnum];


