/* tslint:disable */
/* eslint-disable */
/**
 * Neynar API
 * The Neynar API allows you to interact with the Farcaster protocol among other things. See the [Neynar docs](https://docs.neynar.com/reference) for more details.
 *
 * The version of the OpenAPI document: 3.169.0
 * Contact: team@neynar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UploadTokenMetadataRequestTokensInnerMetadataAttributesInner } from './upload-token-metadata-request-tokens-inner-metadata-attributes-inner';

export interface UploadTokenMetadataRequestTokensInnerMetadata {
    'name': string;
    'description'?: string;
    'image': string;
    'external_url'?: string;
    'animation_url'?: string;
    'background_color'?: string;
    'youtube_url'?: string;
    'attributes'?: Array<UploadTokenMetadataRequestTokensInnerMetadataAttributesInner>;
}

