/* tslint:disable */
/* eslint-disable */
/**
 * Neynar API
 * The Neynar API allows you to interact with the Farcaster protocol among other things. See the [Neynar docs](https://docs.neynar.com/reference) for more details.
 *
 * The version of the OpenAPI document: 3.128.0
 * Contact: team@neynar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserPro
 */
export interface UserPro {
    /**
     * The subscription status of the user
     * @type {string}
     * @memberof UserPro
     */
    'status': UserProStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof UserPro
     */
    'subscribed_at': string;
    /**
     * 
     * @type {string}
     * @memberof UserPro
     */
    'expires_at': string;
}

export const UserProStatusEnum = {
    Subscribed: 'subscribed',
    Unsubscribed: 'unsubscribed'
} as const;

export type UserProStatusEnum = typeof UserProStatusEnum[keyof typeof UserProStatusEnum];


