/* tslint:disable */
/* eslint-disable */
/**
 * Neynar API
 * The Neynar API allows you to interact with the Farcaster protocol among other things. See the [Neynar docs](https://docs.neynar.com/reference) for more details.
 *
 * The version of the OpenAPI document: 3.179.0
 * Contact: team@neynar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WebhookSubscriptionFilters } from './webhook-subscription-filters';

export interface WebhookSubscription {
    'created_at': string;
    'filters': WebhookSubscriptionFilters;
    'object': WebhookSubscriptionObjectEnum;
    'subscription_id': string;
    'updated_at': string;
}

export const WebhookSubscriptionObjectEnum = {
    WebhookSubscription: 'webhook_subscription'
} as const;

export type WebhookSubscriptionObjectEnum = typeof WebhookSubscriptionObjectEnum[keyof typeof WebhookSubscriptionObjectEnum];


